[package]
name = "chatroom"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1", features = ["derive"]}
time = {version = "0.3", features = ["formatting", "parsing", "local-offset", "serde"]}
